/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ozaki' at '18/06/07 21:49' with Gradle 2.14.1
 *
 * @author ozaki, @date 18/06/07 21:49
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
